# Generated by Django 4.1.7 on 2023-03-16 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlistsong',
            name='playlist',
        ),
        migrations.RemoveField(
            model_name='playlistsong',
            name='song',
        ),
        migrations.DeleteModel(
            name='Playlist',
        ),
        migrations.DeleteModel(
            name='PlaylistSong',
        ),
    ]
